version: 2.1

jobs:
  publish:
    docker:
      - image: oryd/sdk:v0.0.39
    working_directory: /sdk
    steps:
      - checkout
      - run: |
          if [ -z "$(git log -1 --pretty=%B | grep 'Add spec for' | grep -v '.pre.')" ]; then
              circleci-agent step halt
          fi
      - run: ./scripts/init.sh
      - run: ./scripts/generate.sh
      - run: ./scripts/release.sh

workflows:
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
