npmName: "@oryd/$PROJECT-client"
npmVersion: $VERSION
# typescriptThreePlus: true
#npmRepository: https://github.com/ory/sdk.git
supportsES6: true
ensureUniqueParams: true
modelPropertyNaming: original
